spring:
  application:
    name: devoot-backend
  profiles:
    active: ${PROFILE}
  elasticsearch:
    uris: http://elastic:${ELASTIC_PASSWORD}@${ELASTICSEARCH_HOST}:9200
    connection-timeout: 5000
    socket-timeout: 3000
    ssl:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
s3:
  file:
    salt: ${S3_FILE_SALT}

firebase:
  config:
    path: src/main/resources/firebase-adminsdk.json

logging:
  level:
    org:
      springframework:
        security: DEBUG
    #    root: DEBUG
    com.google.firebase.auth: DEBUG
    com.gamee.devoot_backend.common.scheduler: DEBUG
#    org.springframework.web: DEBUG
